#!/usr/bin/bash

rm -rf ~/.config/nvim
ln -s "$(pwd)/nvim" ~/.config/nvim

rm -rf ~/.config/tmux
ln -s "$(pwd)/tmux" ~/.config/tmux

echo "source $(pwd)/bash/.bash_profile" >> ~/.bashrc

source ~/.bashrc

